### PR TITLE
Fix unwrap tuple for exclude_opts

### PR DESCRIPTION
**Pull request by kegan**

### CODE REVIEW

**Comment by bitprophet** [comment]
Thanks! Not sure why this went unnoticed as this was supposed to be a straight port from v1's contrib.

**Comment by kegan** [comment]
Thank you for creating such awesome projects! I have been a Fabric user for many many years. Just switch all my projects to Fabric/Invoke.

**Comment by bitprophet** [comment]
Hm, that'll teach me to try using github's fancy schmancy conflict resolution. Managed to delete a line by mistake.

Gonna just do my usual and cherry pick your original commit and manually close.

**Comment by bitprophet** [comment]
Commit's been cherry-picked (to the 1.0 branch so far). Found a second yak herd hiding over the next ridge...hopefully mostly done with it now. Travis seems to be having a bad evening too. We'll see what tomorrow brings.

I'd say this is the most incidental work I've done in order to merge a one-character change, but I suspect it's only 2nd or 3rd place 😂

**Comment by bitprophet** [comment]
Guess Github straight up ignores `closes #XXX` for PRs? 1.0 is finally green on Travis and I added a changelog entry so we're good - thanks again!

**Pull request closed without merging**
