### PR TITLE
Replaced some calls to the removed succeeded attribute

### PR DESCRIPTION
**Pull request by ldelelis**
According to documentation, the correct way is to consult 'ok' now

### CODE REVIEW

**Comment by bitprophet** [comment]
Thanks for the catch!

**Comment by shapeace** [comment]
@bitprophet Why don't you apply current version to PyPi repository?

**Comment by bitprophet** [comment]
1.0.1 is on PyPI now! http://fabric-patchwork.readthedocs.io/en/latest/changelog.html#1.0.1

**Comment by shapeace** [comment]
@bitprophet Thank you for your fast apply. Have a good day. bro.

**Pull request merged**
